// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkZM15MEIOTODqwEG7NS6gB4irNk4zKIU',
    appId: '1:864617191147:web:a9723620f3cf3b8734d0ae',
    messagingSenderId: '864617191147',
    projectId: 'dominoes-counter',
    authDomain: 'dominoes-counter.firebaseapp.com',
    storageBucket: 'dominoes-counter.appspot.com',
    measurementId: 'G-JFTDJV51R3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrR0tmg94HFU9w03YsXwMd50nu4k0ys_Y',
    appId: '1:864617191147:android:24e6f510f04e2b5e34d0ae',
    messagingSenderId: '864617191147',
    projectId: 'dominoes-counter',
    storageBucket: 'dominoes-counter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCB13tBsxkAEZvdQc9Ukuz6j2uDljToxrg',
    appId: '1:864617191147:ios:6b1e2de0f94cf51534d0ae',
    messagingSenderId: '864617191147',
    projectId: 'dominoes-counter',
    storageBucket: 'dominoes-counter.appspot.com',
    iosBundleId: 'com.example.domenosCounter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCB13tBsxkAEZvdQc9Ukuz6j2uDljToxrg',
    appId: '1:864617191147:ios:6e7fb40e5c9d3e8d34d0ae',
    messagingSenderId: '864617191147',
    projectId: 'dominoes-counter',
    storageBucket: 'dominoes-counter.appspot.com',
    iosBundleId: 'com.example.domenosCounter.RunnerTests',
  );
}
